version: '3.8'
services:
  lss-training-api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./credentials:/app/credentials:ro
      - token-data:/app/token
    environment:
      - GOOGLE_CREDENTIALS_FILE=/app/credentials/client_secret.json
      - SPREADSHEET_ID=${SPREADSHEET_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=INFO
      - MAX_WORKERS=4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  token-data: 