[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python -c \"import os; from uvicorn import run; port = int(os.getenv('PORT', '8000')); run('src.api:app', host='0.0.0.0', port=port, reload=False)\"" 